
# SEO settings
title: ""
title2: "辉橦一班" #"X.H." # default: ""
description: "Recently focus on audio device."
keywords: "photography, software, audio, github, SEO, blog, web, minimalist, ruby, python"
url: # site url
# baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo:
disqus_shortname:
twitter_username:
comments: true

# Build settings
#permalink   : /:year/:title/
permalink:        /pages/:year-:month-:day-:title.html  #pretty
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Zhou Xuhui"
  job      : "DIYer"
  bio      : "also I am a shutterbug, a DIYer, an audiophile, a software engineer. I am writing this blog in Chinese and Chinglish."
  thumb    :
  email    : mail@zhouxuhui.com
  url      : ""
  github   : http://github.com/xuhui
  twitter  :
  facebook :
  linkedin :

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["vendor", "gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
